server:
    port: 8080
    address: localhost

spring:
    profiles: prod
    datasource:
        dataSourceClassName: org.postgresql.ds.PGSimpleDataSource
        url: jdbc:postgresql://127.0.0.1:5432/surebet
        databaseName: 
        serverName: 
        username: postgres
        password: eleazar

    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        database: POSTGRESQL
        openInView: false
        show_sql: false
        generate-ddl: false
        hibernate:
            ddl-auto: none
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            

metrics:
    jmx.enabled: true
    graphite:
        enabled: false
        host:
        port:

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 256M
        