server:
    port: 8080
    address: localhost

spring:
    profiles: dev
    datasource:
        dataSourceClassName: org.h2.jdbcx.JdbcDataSource
        url: jdbc:h2:tcp://localhost/~/test
        databaseName: 
        serverName: 
        username: sa
        password:

    jpa:
        database-platform: org.hibernate.dialect.H2Dialect
        database: H2
        openInView: false
        show_sql: true
        generate-ddl: true
        hibernate:
            ddl-auto: update
            naming-strategy: org.hibernate.cfg.EJB3NamingStrategy
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: true
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory

metrics:
    jmx.enabled: true

cache:
    timeToLiveSeconds: 3600
    ehcache:
        maxBytesLocalHeap: 16M
        